### ISSUE TITLE
Running examples input_file_python.nc

### ISSUE THREAD

**Issue by hidayatmn378** [gher-uliege/DINCAE#13]
**Describe the bug**

Error when running the original examples 

**To Reproduce**

Please provide a minimal code example which reproduces the behavior (bug, performance regression, ...).

**Environment**

 - operating system: Ubuntu 16.04.7 LTS
 - Python version 3.9.7 
 - Tensorflow version 2.10.0
 - DINCAE version v1.1.0 (Latest)

**Full output**

In case of an error, please paste the full error message and stack trace.
`
2023-02-04 11:40:35.989971: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA

To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-04 11:40:37.278685: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA

To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-04 11:40:37.279681: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2023-02-04 11:40:37.280860: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance

varname  SST (3, 3)
data shape:  (3, 3, 3)
data range:  0.0 0.0
sz  (3, 3, 3)
sz  (3, 3, 3)
Number of input variables:  10
regularization_L2_beta  0
enc_nfilter_internal  [16, 24, 36, 54]
nvar  10
nepoch_keep_missing  0

Traceback (most recent call last):
  File "/home/ocean/DINCAE-master/run_DINCAE.py", line 10, in <module>
    DINCAE.reconstruct_gridded_nc(filename,varname,outdir)
  File "/home/ocean/DINCAE-master/DINCAE/__init__.py", line 733, in reconstruct_gridded_nc
    reconstruct(
  File "/home/ocean/DINCAE-master/DINCAE/__init__.py", line 404, in reconstruct
    train_iterator_handle = sess.run(train_iterator.string_handle())
AttributeError: 'OwnedIterator' object has no attribute 'string_handle'
`
**Input file**

Run the shell command `ncdump -h myfile.nc` and paste the output here.
`
ocean@ocean-HP-EliteDesk-800-G1-TWR:~/DINCAE-master/examples$ ncdump -h input_file_python.nc 
netcdf input_file_python {
dimensions:
	lon = 3 ;
	lat = 3 ;
	time = UNLIMITED ; // (3 currently)
variables:
	float lon(lon) ;
	float lat(lat) ;
	float time(time) ;
		time:units = "days since 1900-01-01 00:00:00" ;
	float SST(time, lat, lon) ;
		SST:_FillValue = -9999.f ;
	int mask(lat, lon) ;
		mask:comment = "one means the data location is valid (e.g. sea for SST), zero the location is invalid (e.g. land for SST)" ;

// global attributes:
		:_NCProperties = "version=2,netcdf=4.8.1,hdf5=1.10.6" ;
}
`

**Comment by hidayatmn378** [comment]
Never mind. It works after I create the new env and install the libraries based on the README.md version.
